version: '3.4'
services:
  registry.wvoelkl.com:
    image: registry:2
    restart: always
    ports:
    - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /opt/data/registry/:/data
      - /opt/data/auth/registry.passwd:/auth/registry.passwd:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    networks:
      - authenticatedNet
#Nginx Service
  www.wvoelkl.com:
    image: nginx:alpine
    container_name: www.wvoelkl.com
    restart: unless-stopped
    environment:
      - ENV=development
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/log:/var/log/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro        
        #      - ./web/site:/var/www/html/:ro
    networks:
      - authenticatedNet
      - secureNet
#    entrypoint: ["sh", "-c", "sleep 2073600"]
  web.wvoelkl.com:
    image: bitnami/apache:latest
    container_name: site
    restart: unless-stopped
    volumes: 
      - /opt/data/site:/app
      - ./web/conf:/vhosts/my_vhost.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APACHE_HTTP_PORT_NUMBER=8081
#    ports:
#     - 8081:8081
    networks:
     - authenticatedNet
  login.wvoelkl.com:
    image: voucher/vouch-proxy
    restart: unless-stopped
#    ports:
#      - 9090:9090
    volumes:
      - /opt/data/vouch/config.yml:/config/config.yml:ro
      - /opt/data/vouch/db:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    networks:
      - secureNet
  mongo:
    image: bitnami/mongodb:latest
    ports:
      27017:27017
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/data/mongodb:/data/db
    networks:
      - authenticatedNet
networks:
  authenticatedNet:
    driver: bridge
  secureNet:
    driver: bridge
